version: '3.8'

services:

  server:
    image: ghcr.io/silkkycloud/pleroma:2.4.2
    hostname: pleroma
    networks:
      - public
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      update_config:
        failure_action: rollback
        order: start-first
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.pleroma.rule=Host(`${HOSTNAME}`)"
        - "traefik.http.routers.pleroma.entrypoints=websecure"
        - "traefik.http.routers.pleroma.tls=true"
        - "traefik.http.routers.pleroma.service=pleroma-service"
        # Service
        - "traefik.http.services.pleroma-service.loadbalancer.server.port=4000"
    volumes:
      - uploads:/var/lib/pleroma/uploads
    configs:
      - source: dynamic-config
        target: /var/lib/pleroma/config.exs
        uid: "1000"
        gid: "1000"
    environment:
      # Database
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=pleroma
      - POSTGRES_USER=pleroma
      - POSTGRES_PASS=${POSTGRESQL_PASSWORD}
      # Mailer
      - SMTP_HOST=${MAIL_HOST}
      - SMTP_PORT=${MAIL_PORT}
      - SMTP_USERNAME=${MAIL_USERNAME}
      - SMTP_PASSWORD=${MAIL_PASSWORD}
      # General
      - DOMAIN=${HOSTNAME}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - INSTANCE_DESCRIPTION=${INSTANCE_DESCRIPTION}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - NOTIFY_EMAIL=${ADMIN_EMAIL}

  postgresql:
    image: postgres:14-alpine
    hostname: postgresql
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          cpus: '0.2'
          memory: 512M
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pleroma
      - POSTGRES_USER=pleroma
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}

networks:
  public:
    external: true

  backend:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450

volumes:
  database:
  uploads:

configs:
  dynamic-config:
    file: ./config.exs