name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master 
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      PLEROMA_GIT_REPO: https://git.pleroma.social/pleroma/pleroma.git
      PLEROMA_VERSION: stable
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get hash of latest image
        run: docker pull alpine:edge && docker inspect --format='{{index .RepoDigests 0}}' alpine:edge > dockerhash.txt
      - name: cache docker cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/dockerhash.txt') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/silkkycloud/pleroma:latest
          cache-from: type=local,src=cache
          cache-to: type=local,dest=cache
